/*
* generated by Xtext
*/
package gov.nasa.ensemble.dictionary.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class XDictionaryStandaloneSetup extends XDictionaryStandaloneSetupGenerated{

	public static void doSetup() {
		new XDictionaryStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

