/*
 * generated by Xtext
 */
package gov.nasa.ensemble.dictionary.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XDictionaryRuntimeModule extends gov.nasa.ensemble.dictionary.xtext.AbstractXDictionaryRuntimeModule {

}
