/*
* generated by Xtext
*/
package gov.nasa.ensemble.dictionary.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class XDictionaryUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return gov.nasa.ensemble.dictionary.xtext.ui.internal.XDictionaryActivator.getInstance().getInjector("gov.nasa.ensemble.dictionary.xtext.XDictionary");
	}
	
}
