/*
* generated by Xtext
*/
package gov.nasa.ensemble.dictionary.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import gov.nasa.ensemble.dictionary.xtext.services.XDictionaryGrammarAccess;

public class XDictionaryParser extends AbstractContentAssistParser {
	
	@Inject
	private XDictionaryGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected gov.nasa.ensemble.dictionary.xtext.ui.contentassist.antlr.internal.InternalXDictionaryParser createParser() {
		gov.nasa.ensemble.dictionary.xtext.ui.contentassist.antlr.internal.InternalXDictionaryParser result = new gov.nasa.ensemble.dictionary.xtext.ui.contentassist.antlr.internal.InternalXDictionaryParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getDefinitionAccess().getAlternatives(), "rule__Definition__Alternatives");
					put(grammarAccess.getParameterDefAccess().getAlternatives(), "rule__ParameterDef__Alternatives");
					put(grammarAccess.getBooleanAccess().getAlternatives(), "rule__Boolean__Alternatives");
					put(grammarAccess.getRequirementAccess().getAlternatives(), "rule__Requirement__Alternatives");
					put(grammarAccess.getEffectAccess().getAlternatives(), "rule__Effect__Alternatives");
					put(grammarAccess.getResourceDefAccess().getAlternatives(), "rule__ResourceDef__Alternatives");
					put(grammarAccess.getDictionaryAccess().getGroup(), "rule__Dictionary__Group__0");
					put(grammarAccess.getDictionaryAccess().getGroup_0_0(), "rule__Dictionary__Group_0_0__0");
					put(grammarAccess.getDictionaryAccess().getGroup_0_1(), "rule__Dictionary__Group_0_1__0");
					put(grammarAccess.getDictionaryAccess().getGroup_0_2(), "rule__Dictionary__Group_0_2__0");
					put(grammarAccess.getDictionaryAccess().getGroup_0_3(), "rule__Dictionary__Group_0_3__0");
					put(grammarAccess.getDictionaryAccess().getGroup_0_4(), "rule__Dictionary__Group_0_4__0");
					put(grammarAccess.getDictionaryAccess().getGroup_0_5(), "rule__Dictionary__Group_0_5__0");
					put(grammarAccess.getEnumDefAccess().getGroup(), "rule__EnumDef__Group__0");
					put(grammarAccess.getEnumValueAccess().getGroup(), "rule__EnumValue__Group__0");
					put(grammarAccess.getEnumValueAccess().getGroup_1_0(), "rule__EnumValue__Group_1_0__0");
					put(grammarAccess.getEnumValueAccess().getGroup_1_1(), "rule__EnumValue__Group_1_1__0");
					put(grammarAccess.getEnumValueAccess().getGroup_1_2(), "rule__EnumValue__Group_1_2__0");
					put(grammarAccess.getAttributeDefAccess().getGroup(), "rule__AttributeDef__Group__0");
					put(grammarAccess.getAttributeDefAccess().getGroup_4_0(), "rule__AttributeDef__Group_4_0__0");
					put(grammarAccess.getAttributeDefAccess().getGroup_4_1(), "rule__AttributeDef__Group_4_1__0");
					put(grammarAccess.getAttributeDefAccess().getGroup_4_2(), "rule__AttributeDef__Group_4_2__0");
					put(grammarAccess.getAttributeDefAccess().getGroup_4_3(), "rule__AttributeDef__Group_4_3__0");
					put(grammarAccess.getAttributeDefAccess().getGroup_4_4(), "rule__AttributeDef__Group_4_4__0");
					put(grammarAccess.getAttributeDefAccess().getGroup_4_5(), "rule__AttributeDef__Group_4_5__0");
					put(grammarAccess.getAttributeDefAccess().getGroup_4_6(), "rule__AttributeDef__Group_4_6__0");
					put(grammarAccess.getReferenceDefAccess().getGroup(), "rule__ReferenceDef__Group__0");
					put(grammarAccess.getReferenceDefAccess().getGroup_4_0(), "rule__ReferenceDef__Group_4_0__0");
					put(grammarAccess.getReferenceDefAccess().getGroup_4_1(), "rule__ReferenceDef__Group_4_1__0");
					put(grammarAccess.getReferenceDefAccess().getGroup_4_2(), "rule__ReferenceDef__Group_4_2__0");
					put(grammarAccess.getReferenceDefAccess().getGroup_4_3(), "rule__ReferenceDef__Group_4_3__0");
					put(grammarAccess.getActivityDefAccess().getGroup(), "rule__ActivityDef__Group__0");
					put(grammarAccess.getActivityDefAccess().getGroup_3_0(), "rule__ActivityDef__Group_3_0__0");
					put(grammarAccess.getActivityDefAccess().getGroup_3_1(), "rule__ActivityDef__Group_3_1__0");
					put(grammarAccess.getActivityDefAccess().getGroup_3_2(), "rule__ActivityDef__Group_3_2__0");
					put(grammarAccess.getActivityDefAccess().getGroup_3_3(), "rule__ActivityDef__Group_3_3__0");
					put(grammarAccess.getActivityDefAccess().getGroup_3_4(), "rule__ActivityDef__Group_3_4__0");
					put(grammarAccess.getAnnotationAccess().getGroup(), "rule__Annotation__Group__0");
					put(grammarAccess.getNumericRequirementAccess().getGroup(), "rule__NumericRequirement__Group__0");
					put(grammarAccess.getStateRequirementAccess().getGroup(), "rule__StateRequirement__Group__0");
					put(grammarAccess.getStateRequirementAccess().getGroup_1_0(), "rule__StateRequirement__Group_1_0__0");
					put(grammarAccess.getStateRequirementAccess().getGroup_1_1(), "rule__StateRequirement__Group_1_1__0");
					put(grammarAccess.getActivityGroupDefAccess().getGroup(), "rule__ActivityGroupDef__Group__0");
					put(grammarAccess.getObjectDefAccess().getGroup(), "rule__ObjectDef__Group__0");
					put(grammarAccess.getNumericResourceAccess().getGroup(), "rule__NumericResource__Group__0");
					put(grammarAccess.getStateResourceAccess().getGroup(), "rule__StateResource__Group__0");
					put(grammarAccess.getClaimableResourceAccess().getGroup(), "rule__ClaimableResource__Group__0");
					put(grammarAccess.getSharableResourceAccess().getGroup(), "rule__SharableResource__Group__0");
					put(grammarAccess.getSummaryResourceAccess().getGroup(), "rule__SummaryResource__Group__0");
					put(grammarAccess.getDictionaryAccess().getNameAssignment_0_0_2(), "rule__Dictionary__NameAssignment_0_0_2");
					put(grammarAccess.getDictionaryAccess().getAuthorAssignment_0_1_2(), "rule__Dictionary__AuthorAssignment_0_1_2");
					put(grammarAccess.getDictionaryAccess().getDateAssignment_0_2_2(), "rule__Dictionary__DateAssignment_0_2_2");
					put(grammarAccess.getDictionaryAccess().getDescriptionAssignment_0_3_2(), "rule__Dictionary__DescriptionAssignment_0_3_2");
					put(grammarAccess.getDictionaryAccess().getVersionAssignment_0_4_2(), "rule__Dictionary__VersionAssignment_0_4_2");
					put(grammarAccess.getDictionaryAccess().getDomainAssignment_0_5_2(), "rule__Dictionary__DomainAssignment_0_5_2");
					put(grammarAccess.getDictionaryAccess().getDefinitionsAssignment_1(), "rule__Dictionary__DefinitionsAssignment_1");
					put(grammarAccess.getEnumDefAccess().getNameAssignment_1(), "rule__EnumDef__NameAssignment_1");
					put(grammarAccess.getEnumDefAccess().getValuesAssignment_3(), "rule__EnumDef__ValuesAssignment_3");
					put(grammarAccess.getEnumValueAccess().getNameAssignment_1_0_2(), "rule__EnumValue__NameAssignment_1_0_2");
					put(grammarAccess.getEnumValueAccess().getColorAssignment_1_1_2(), "rule__EnumValue__ColorAssignment_1_1_2");
					put(grammarAccess.getEnumValueAccess().getLiteralAssignment_1_2_2(), "rule__EnumValue__LiteralAssignment_1_2_2");
					put(grammarAccess.getAttributeDefAccess().getNameAssignment_1(), "rule__AttributeDef__NameAssignment_1");
					put(grammarAccess.getAttributeDefAccess().getTypeAssignment_2(), "rule__AttributeDef__TypeAssignment_2");
					put(grammarAccess.getAttributeDefAccess().getDefaultValueLiteralAssignment_4_0_2(), "rule__AttributeDef__DefaultValueLiteralAssignment_4_0_2");
					put(grammarAccess.getAttributeDefAccess().getDescriptionAssignment_4_1_2(), "rule__AttributeDef__DescriptionAssignment_4_1_2");
					put(grammarAccess.getAttributeDefAccess().getShortDescriptionAssignment_4_2_2(), "rule__AttributeDef__ShortDescriptionAssignment_4_2_2");
					put(grammarAccess.getAttributeDefAccess().getUnitsAssignment_4_3_2(), "rule__AttributeDef__UnitsAssignment_4_3_2");
					put(grammarAccess.getAttributeDefAccess().getDisplayNameAssignment_4_4_2(), "rule__AttributeDef__DisplayNameAssignment_4_4_2");
					put(grammarAccess.getAttributeDefAccess().getCategoryAssignment_4_5_2(), "rule__AttributeDef__CategoryAssignment_4_5_2");
					put(grammarAccess.getAttributeDefAccess().getParameterNameAssignment_4_6_2(), "rule__AttributeDef__ParameterNameAssignment_4_6_2");
					put(grammarAccess.getAttributeDefAccess().getAnnotationsAssignment_5(), "rule__AttributeDef__AnnotationsAssignment_5");
					put(grammarAccess.getReferenceDefAccess().getNameAssignment_1(), "rule__ReferenceDef__NameAssignment_1");
					put(grammarAccess.getReferenceDefAccess().getTypeAssignment_2(), "rule__ReferenceDef__TypeAssignment_2");
					put(grammarAccess.getReferenceDefAccess().getDescriptionAssignment_4_0_2(), "rule__ReferenceDef__DescriptionAssignment_4_0_2");
					put(grammarAccess.getReferenceDefAccess().getDisplayNameAssignment_4_1_2(), "rule__ReferenceDef__DisplayNameAssignment_4_1_2");
					put(grammarAccess.getReferenceDefAccess().getCategoryAssignment_4_2_2(), "rule__ReferenceDef__CategoryAssignment_4_2_2");
					put(grammarAccess.getReferenceDefAccess().getContainmentAssignment_4_3_2(), "rule__ReferenceDef__ContainmentAssignment_4_3_2");
					put(grammarAccess.getReferenceDefAccess().getAnnotationsAssignment_5(), "rule__ReferenceDef__AnnotationsAssignment_5");
					put(grammarAccess.getReferenceDefAccess().getRequirementsAssignment_6(), "rule__ReferenceDef__RequirementsAssignment_6");
					put(grammarAccess.getReferenceDefAccess().getEffectsAssignment_7(), "rule__ReferenceDef__EffectsAssignment_7");
					put(grammarAccess.getActivityDefAccess().getNameAssignment_1(), "rule__ActivityDef__NameAssignment_1");
					put(grammarAccess.getActivityDefAccess().getDescriptionAssignment_3_0_2(), "rule__ActivityDef__DescriptionAssignment_3_0_2");
					put(grammarAccess.getActivityDefAccess().getCategoryAssignment_3_1_2(), "rule__ActivityDef__CategoryAssignment_3_1_2");
					put(grammarAccess.getActivityDefAccess().getDurationAssignment_3_2_2(), "rule__ActivityDef__DurationAssignment_3_2_2");
					put(grammarAccess.getActivityDefAccess().getDisplayNameAssignment_3_3_2(), "rule__ActivityDef__DisplayNameAssignment_3_3_2");
					put(grammarAccess.getActivityDefAccess().getHiddenParamsAssignment_3_4_2(), "rule__ActivityDef__HiddenParamsAssignment_3_4_2");
					put(grammarAccess.getActivityDefAccess().getAnnotationsAssignment_4(), "rule__ActivityDef__AnnotationsAssignment_4");
					put(grammarAccess.getActivityDefAccess().getParametersAssignment_5(), "rule__ActivityDef__ParametersAssignment_5");
					put(grammarAccess.getActivityDefAccess().getRequirementsAssignment_6(), "rule__ActivityDef__RequirementsAssignment_6");
					put(grammarAccess.getActivityDefAccess().getEffectsAssignment_7(), "rule__ActivityDef__EffectsAssignment_7");
					put(grammarAccess.getAnnotationAccess().getSourceAssignment_1(), "rule__Annotation__SourceAssignment_1");
					put(grammarAccess.getAnnotationAccess().getKeyAssignment_2(), "rule__Annotation__KeyAssignment_2");
					put(grammarAccess.getAnnotationAccess().getValueAssignment_3(), "rule__Annotation__ValueAssignment_3");
					put(grammarAccess.getNumericRequirementAccess().getExpressionAssignment_3(), "rule__NumericRequirement__ExpressionAssignment_3");
					put(grammarAccess.getStateRequirementAccess().getDefinitionAssignment_1_0_2(), "rule__StateRequirement__DefinitionAssignment_1_0_2");
					put(grammarAccess.getStateRequirementAccess().getRequiredStateAssignment_1_1_2(), "rule__StateRequirement__RequiredStateAssignment_1_1_2");
					put(grammarAccess.getActivityGroupDefAccess().getNameAssignment_1(), "rule__ActivityGroupDef__NameAssignment_1");
					put(grammarAccess.getActivityGroupDefAccess().getAnnotationsAssignment_3(), "rule__ActivityGroupDef__AnnotationsAssignment_3");
					put(grammarAccess.getActivityGroupDefAccess().getParametersAssignment_4(), "rule__ActivityGroupDef__ParametersAssignment_4");
					put(grammarAccess.getObjectDefAccess().getNameAssignment_1(), "rule__ObjectDef__NameAssignment_1");
					put(grammarAccess.getNumericResourceAccess().getNameAssignment_1(), "rule__NumericResource__NameAssignment_1");
					put(grammarAccess.getStateResourceAccess().getNameAssignment_1(), "rule__StateResource__NameAssignment_1");
					put(grammarAccess.getClaimableResourceAccess().getNameAssignment_1(), "rule__ClaimableResource__NameAssignment_1");
					put(grammarAccess.getSharableResourceAccess().getNameAssignment_1(), "rule__SharableResource__NameAssignment_1");
					put(grammarAccess.getSummaryResourceAccess().getNameAssignment_1(), "rule__SummaryResource__NameAssignment_1");
					put(grammarAccess.getDictionaryAccess().getUnorderedGroup_0(), "rule__Dictionary__UnorderedGroup_0");
					put(grammarAccess.getEnumValueAccess().getUnorderedGroup_1(), "rule__EnumValue__UnorderedGroup_1");
					put(grammarAccess.getAttributeDefAccess().getUnorderedGroup_4(), "rule__AttributeDef__UnorderedGroup_4");
					put(grammarAccess.getReferenceDefAccess().getUnorderedGroup_4(), "rule__ReferenceDef__UnorderedGroup_4");
					put(grammarAccess.getActivityDefAccess().getUnorderedGroup_3(), "rule__ActivityDef__UnorderedGroup_3");
					put(grammarAccess.getStateRequirementAccess().getUnorderedGroup_1(), "rule__StateRequirement__UnorderedGroup_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			gov.nasa.ensemble.dictionary.xtext.ui.contentassist.antlr.internal.InternalXDictionaryParser typedParser = (gov.nasa.ensemble.dictionary.xtext.ui.contentassist.antlr.internal.InternalXDictionaryParser) parser;
			typedParser.entryRuleDictionary();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public XDictionaryGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XDictionaryGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
