/*
* generated by Xtext
*/
package gov.nasa.ensemble.dictionary.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import gov.nasa.ensemble.dictionary.xtext.services.XDictionaryGrammarAccess;

public class XDictionaryParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private XDictionaryGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected gov.nasa.ensemble.dictionary.xtext.parser.antlr.internal.InternalXDictionaryParser createParser(XtextTokenStream stream) {
		return new gov.nasa.ensemble.dictionary.xtext.parser.antlr.internal.InternalXDictionaryParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Dictionary";
	}
	
	public XDictionaryGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XDictionaryGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
