<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="member"
    nsURI="platform:/resource/gov.nasa.ensemble.core.plan.resources/model/ResourceMembers.ecore"
    nsPrefix="member">
  <eClassifiers xsi:type="ecore:EClass" name="Conditions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="time"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="description"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editable" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="claims" upperBound="-1"
        eType="#//Claim" containment="true" resolveProxies="false" eOpposite="#//Claim/conditions">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="Claim"/>
        <details key="namespace" value="##targetNamespace"/>
        <details key="group" value="#group:0"/>
      </eAnnotations>
      <eAnnotations source="detail">
        <details key="table" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="powerLoads" upperBound="-1"
        eType="#//PowerLoad" containment="true" resolveProxies="false" eOpposite="#//PowerLoad/conditions">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="PowerLoad"/>
        <details key="namespace" value="##targetNamespace"/>
        <details key="group" value="#group:0"/>
      </eAnnotations>
      <eAnnotations source="detail">
        <details key="table" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="numericResources" upperBound="-1"
        eType="#//NumericResource" containment="true" resolveProxies="false" eOpposite="#//NumericResource/conditions">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="NumericResource"/>
        <details key="namespace" value="##targetNamespace"/>
        <details key="group" value="#group:0"/>
      </eAnnotations>
      <eAnnotations source="detail">
        <details key="table" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateResources" upperBound="-1"
        eType="#//StateResource" containment="true" resolveProxies="false" eOpposite="#//StateResource/conditions">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="StateResource"/>
        <details key="namespace" value="##targetNamespace"/>
        <details key="group" value="#group:0"/>
      </eAnnotations>
      <eAnnotations source="detail">
        <details key="table" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sharableResources" upperBound="-1"
        eType="#//SharableResource" containment="true" resolveProxies="false" eOpposite="#//SharableResource/conditions">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="SharableResource"/>
        <details key="namespace" value="##targetNamespace"/>
        <details key="group" value="#group:0"/>
      </eAnnotations>
      <eAnnotations source="detail">
        <details key="table" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="undefinedResources" upperBound="-1"
        eType="#//UndefinedResource" containment="true" eOpposite="#//UndefinedResource/conditions">
      <eAnnotations source="detail">
        <details key="table" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" eType="#//ResourceConditionsMember"
        eOpposite="#//ResourceConditionsMember/conditions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Claim" eSuperTypes="#//NamedCondition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="used" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="used"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" eType="#//Conditions"
        eOpposite="#//Conditions/claims"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedCondition">
    <eOperations name="getConditions" eType="#//Conditions"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="name"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumericResource" eSuperTypes="#//NamedCondition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="float" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Float"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="float"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" eType="#//Conditions"
        eOpposite="#//Conditions/numericResources"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PowerLoad" eSuperTypes="#//NamedCondition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="state"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" eType="#//Conditions"
        eOpposite="#//Conditions/powerLoads"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceConditionsMember" eSuperTypes="../../gov.nasa.ensemble.core.model.plan/model/Planning.ecore#//EMember">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" upperBound="-1"
        eType="#//Conditions" containment="true" eOpposite="#//Conditions/member"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SharableResource" eSuperTypes="#//NamedCondition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="used" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="used"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" eType="#//Conditions"
        eOpposite="#//Conditions/sharableResources"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateResource" eSuperTypes="#//NamedCondition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="state"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" eType="#//Conditions"
        eOpposite="#//Conditions/stateResources"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UndefinedResource" eSuperTypes="#//NamedCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" eType="#//Conditions"
        eOpposite="#//Conditions/undefinedResources"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueLiteral" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
