/*
 * generated by Xtext
 */
package gov.nasa.ensemble.dictionary.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractXDictionaryValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(gov.nasa.ensemble.dictionary.xtext.xDictionary.XDictionaryPackage.eINSTANCE);
		return result;
	}
}
