<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="timeline"
    nsURI="platform:/resource/gov.nasa.arc.spife.core.plan/model/PlanTimeline.ecore"
    nsPrefix="ptlc">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractPlanSection" abstract="true"
      eSuperTypes="../../gov.nasa.arc.spife/model/Timeline.ecore#//GanttSection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showUnreferecedRow" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureValueRow" eSuperTypes="#//PlanSectionRow">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureName" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueLiteral" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlanReferencedObjectSection" eSuperTypes="#//AbstractPlanSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ../../gov.nasa.ensemble.dictionary/model/Dictionary.ecore#//ObjectDef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlanSection" eSuperTypes="#//AbstractPlanSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" upperBound="-1" eType="#//PlanSectionRow"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlanSectionRow">
    <eOperations name="satisfies" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean">
      <eParameters name="object" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eOperations name="isRelevant" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean">
      <eParameters name="feature" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferencedObjectRow" eSuperTypes="#//PlanSectionRow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
</ecore:EPackage>
