/*******************************************************************************
 * Copyright 2014 United States Government as represented by the
 * Administrator of the National Aeronautics and Space Administration.
 * All Rights Reserved.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package gov.nasa.ensemble.core.detail.emf;

import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.swt.widgets.Composite;

/**
 * Class used for contributing toolbar actions to the widget generated by the table binding factory.
 * This class can also be used to indicate the minimum number of rows that the table should be displayed with
 */
public interface ITableBindingFactoryToolbarContributor {
	/**
	 * Method to contribute toolbar actions to the widget generated by the table binding factory mechanism.
	 * @param composite the parent composite - when toolbar items are created, this composite should be used as the parent.
	 * @param displayName the name of the element upon which your custom action will act.
	 * @param userData a generic holder for any data that your action might need to perform.
	 * @param structuralFeature the feature for which the toolbar item is to be created
	 */
	public void contribute(Composite composite, String displayName, Object userData, EStructuralFeature structuralFeature);
}
