/*
* generated by Xtext
*/
grammar InternalXDictionary;

options {
	superClass=AbstractInternalAntlrParser;
	
}

@lexer::header {
package gov.nasa.ensemble.dictionary.xtext.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package gov.nasa.ensemble.dictionary.xtext.parser.antlr.internal; 

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import gov.nasa.ensemble.dictionary.xtext.services.XDictionaryGrammarAccess;

}

@parser::members {

 	private XDictionaryGrammarAccess grammarAccess;
 	
    public InternalXDictionaryParser(TokenStream input, XDictionaryGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }
    
    @Override
    protected String getFirstRuleName() {
    	return "Dictionary";	
   	}
   	
   	@Override
   	protected XDictionaryGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}
}

@rulecatch { 
    catch (RecognitionException re) { 
        recover(input,re); 
        appendSkippedTokens();
    } 
}




// Entry rule entryRuleDictionary
entryRuleDictionary returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getDictionaryRule()); }
	 iv_ruleDictionary=ruleDictionary 
	 { $current=$iv_ruleDictionary.current; } 
	 EOF 
;

// Rule Dictionary
ruleDictionary returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
((

(
	{ 
	  getUnorderedGroupHelper().enter(grammarAccess.getDictionaryAccess().getUnorderedGroup_0());
	}
	(
		(

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getDictionaryAccess().getUnorderedGroup_0(), 0)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getDictionaryAccess().getUnorderedGroup_0(), 0);
	 				}
					({true}?=>(	otherlv_1='name' 
    {
    	newLeafNode(otherlv_1, grammarAccess.getDictionaryAccess().getNameKeyword_0_0_0());
    }
	otherlv_2='=' 
    {
    	newLeafNode(otherlv_2, grammarAccess.getDictionaryAccess().getEqualsSignKeyword_0_0_1());
    }
(
(
		lv_name_3_0=RULE_ID
		{
			newLeafNode(lv_name_3_0, grammarAccess.getDictionaryAccess().getNameIDTerminalRuleCall_0_0_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getDictionaryRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"name",
        		lv_name_3_0, 
        		"ID");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getDictionaryAccess().getUnorderedGroup_0());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getDictionaryAccess().getUnorderedGroup_0(), 1)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getDictionaryAccess().getUnorderedGroup_0(), 1);
	 				}
					({true}?=>(	otherlv_4='author' 
    {
    	newLeafNode(otherlv_4, grammarAccess.getDictionaryAccess().getAuthorKeyword_0_1_0());
    }
	otherlv_5='=' 
    {
    	newLeafNode(otherlv_5, grammarAccess.getDictionaryAccess().getEqualsSignKeyword_0_1_1());
    }
(
(
		lv_author_6_0=RULE_STRING
		{
			newLeafNode(lv_author_6_0, grammarAccess.getDictionaryAccess().getAuthorSTRINGTerminalRuleCall_0_1_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getDictionaryRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"author",
        		lv_author_6_0, 
        		"STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getDictionaryAccess().getUnorderedGroup_0());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getDictionaryAccess().getUnorderedGroup_0(), 2)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getDictionaryAccess().getUnorderedGroup_0(), 2);
	 				}
					({true}?=>(	otherlv_7='date' 
    {
    	newLeafNode(otherlv_7, grammarAccess.getDictionaryAccess().getDateKeyword_0_2_0());
    }
	otherlv_8='=' 
    {
    	newLeafNode(otherlv_8, grammarAccess.getDictionaryAccess().getEqualsSignKeyword_0_2_1());
    }
(
(
		lv_date_9_0=RULE_STRING
		{
			newLeafNode(lv_date_9_0, grammarAccess.getDictionaryAccess().getDateSTRINGTerminalRuleCall_0_2_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getDictionaryRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"date",
        		lv_date_9_0, 
        		"STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getDictionaryAccess().getUnorderedGroup_0());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getDictionaryAccess().getUnorderedGroup_0(), 3)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getDictionaryAccess().getUnorderedGroup_0(), 3);
	 				}
					({true}?=>(	otherlv_10='description' 
    {
    	newLeafNode(otherlv_10, grammarAccess.getDictionaryAccess().getDescriptionKeyword_0_3_0());
    }
	otherlv_11='=' 
    {
    	newLeafNode(otherlv_11, grammarAccess.getDictionaryAccess().getEqualsSignKeyword_0_3_1());
    }
(
(
		lv_description_12_0=RULE_STRING
		{
			newLeafNode(lv_description_12_0, grammarAccess.getDictionaryAccess().getDescriptionSTRINGTerminalRuleCall_0_3_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getDictionaryRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"description",
        		lv_description_12_0, 
        		"STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getDictionaryAccess().getUnorderedGroup_0());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getDictionaryAccess().getUnorderedGroup_0(), 4)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getDictionaryAccess().getUnorderedGroup_0(), 4);
	 				}
					({true}?=>(	otherlv_13='version' 
    {
    	newLeafNode(otherlv_13, grammarAccess.getDictionaryAccess().getVersionKeyword_0_4_0());
    }
	otherlv_14='=' 
    {
    	newLeafNode(otherlv_14, grammarAccess.getDictionaryAccess().getEqualsSignKeyword_0_4_1());
    }
(
(
		lv_version_15_0=RULE_STRING
		{
			newLeafNode(lv_version_15_0, grammarAccess.getDictionaryAccess().getVersionSTRINGTerminalRuleCall_0_4_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getDictionaryRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"version",
        		lv_version_15_0, 
        		"STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getDictionaryAccess().getUnorderedGroup_0());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getDictionaryAccess().getUnorderedGroup_0(), 5)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getDictionaryAccess().getUnorderedGroup_0(), 5);
	 				}
					({true}?=>(	otherlv_16='domain' 
    {
    	newLeafNode(otherlv_16, grammarAccess.getDictionaryAccess().getDomainKeyword_0_5_0());
    }
	otherlv_17='=' 
    {
    	newLeafNode(otherlv_17, grammarAccess.getDictionaryAccess().getEqualsSignKeyword_0_5_1());
    }
(
(
		lv_domain_18_0=RULE_STRING
		{
			newLeafNode(lv_domain_18_0, grammarAccess.getDictionaryAccess().getDomainSTRINGTerminalRuleCall_0_5_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getDictionaryRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"domain",
        		lv_domain_18_0, 
        		"STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getDictionaryAccess().getUnorderedGroup_0());
	 				}
 				)
			)  

		)+
	  	{getUnorderedGroupHelper().canLeave(grammarAccess.getDictionaryAccess().getUnorderedGroup_0())}?	
	)
)
	{ 
	  getUnorderedGroupHelper().leave(grammarAccess.getDictionaryAccess().getUnorderedGroup_0());
	}

)(
(
		{ 
	        newCompositeNode(grammarAccess.getDictionaryAccess().getDefinitionsDefinitionParserRuleCall_1_0()); 
	    }
		lv_definitions_19_0=ruleDefinition		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getDictionaryRule());
	        }
       		add(
       			$current, 
       			"definitions",
        		lv_definitions_19_0, 
        		"Definition");
	        afterParserOrEnumRuleCall();
	    }

)
)*)
;





// Entry rule entryRuleDefinition
entryRuleDefinition returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getDefinitionRule()); }
	 iv_ruleDefinition=ruleDefinition 
	 { $current=$iv_ruleDefinition.current; } 
	 EOF 
;

// Rule Definition
ruleDefinition returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(
    { 
        newCompositeNode(grammarAccess.getDefinitionAccess().getEnumDefParserRuleCall_0()); 
    }
    this_EnumDef_0=ruleEnumDef
    { 
        $current = $this_EnumDef_0.current; 
        afterParserOrEnumRuleCall();
    }

    |
    { 
        newCompositeNode(grammarAccess.getDefinitionAccess().getParameterDefParserRuleCall_1()); 
    }
    this_ParameterDef_1=ruleParameterDef
    { 
        $current = $this_ParameterDef_1.current; 
        afterParserOrEnumRuleCall();
    }

    |
    { 
        newCompositeNode(grammarAccess.getDefinitionAccess().getActivityDefParserRuleCall_2()); 
    }
    this_ActivityDef_2=ruleActivityDef
    { 
        $current = $this_ActivityDef_2.current; 
        afterParserOrEnumRuleCall();
    }

    |
    { 
        newCompositeNode(grammarAccess.getDefinitionAccess().getActivityGroupDefParserRuleCall_3()); 
    }
    this_ActivityGroupDef_3=ruleActivityGroupDef
    { 
        $current = $this_ActivityGroupDef_3.current; 
        afterParserOrEnumRuleCall();
    }

    |
    { 
        newCompositeNode(grammarAccess.getDefinitionAccess().getObjectDefParserRuleCall_4()); 
    }
    this_ObjectDef_4=ruleObjectDef
    { 
        $current = $this_ObjectDef_4.current; 
        afterParserOrEnumRuleCall();
    }

    |
    { 
        newCompositeNode(grammarAccess.getDefinitionAccess().getResourceDefParserRuleCall_5()); 
    }
    this_ResourceDef_5=ruleResourceDef
    { 
        $current = $this_ResourceDef_5.current; 
        afterParserOrEnumRuleCall();
    }
)
;





// Entry rule entryRuleEnumDef
entryRuleEnumDef returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getEnumDefRule()); }
	 iv_ruleEnumDef=ruleEnumDef 
	 { $current=$iv_ruleEnumDef.current; } 
	 EOF 
;

// Rule EnumDef
ruleEnumDef returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='Enum' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getEnumDefAccess().getEnumKeyword_0());
    }
(
(
		lv_name_1_0=RULE_ID
		{
			newLeafNode(lv_name_1_0, grammarAccess.getEnumDefAccess().getNameIDTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getEnumDefRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"name",
        		lv_name_1_0, 
        		"ID");
	    }

)
)	otherlv_2='{' 
    {
    	newLeafNode(otherlv_2, grammarAccess.getEnumDefAccess().getLeftCurlyBracketKeyword_2());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getEnumDefAccess().getValuesEnumValueParserRuleCall_3_0()); 
	    }
		lv_values_3_0=ruleEnumValue		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getEnumDefRule());
	        }
       		add(
       			$current, 
       			"values",
        		lv_values_3_0, 
        		"EnumValue");
	        afterParserOrEnumRuleCall();
	    }

)
)*	otherlv_4='}' 
    {
    	newLeafNode(otherlv_4, grammarAccess.getEnumDefAccess().getRightCurlyBracketKeyword_4());
    }
)
;





// Entry rule entryRuleEnumValue
entryRuleEnumValue returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getEnumValueRule()); }
	 iv_ruleEnumValue=ruleEnumValue 
	 { $current=$iv_ruleEnumValue.current; } 
	 EOF 
;

// Rule EnumValue
ruleEnumValue returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='Literal' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getEnumValueAccess().getLiteralKeyword_0());
    }
(

(
	{ 
	  getUnorderedGroupHelper().enter(grammarAccess.getEnumValueAccess().getUnorderedGroup_1());
	}
	(
		(

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getEnumValueAccess().getUnorderedGroup_1(), 0)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getEnumValueAccess().getUnorderedGroup_1(), 0);
	 				}
					({true}?=>(	otherlv_2='name' 
    {
    	newLeafNode(otherlv_2, grammarAccess.getEnumValueAccess().getNameKeyword_1_0_0());
    }
	otherlv_3='=' 
    {
    	newLeafNode(otherlv_3, grammarAccess.getEnumValueAccess().getEqualsSignKeyword_1_0_1());
    }
(
(
		lv_name_4_0=RULE_STRING
		{
			newLeafNode(lv_name_4_0, grammarAccess.getEnumValueAccess().getNameSTRINGTerminalRuleCall_1_0_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getEnumValueRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"name",
        		lv_name_4_0, 
        		"STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getEnumValueAccess().getUnorderedGroup_1());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getEnumValueAccess().getUnorderedGroup_1(), 1)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getEnumValueAccess().getUnorderedGroup_1(), 1);
	 				}
					({true}?=>(	otherlv_5='color' 
    {
    	newLeafNode(otherlv_5, grammarAccess.getEnumValueAccess().getColorKeyword_1_1_0());
    }
	otherlv_6='=' 
    {
    	newLeafNode(otherlv_6, grammarAccess.getEnumValueAccess().getEqualsSignKeyword_1_1_1());
    }
(
(
		lv_color_7_0=RULE_STRING
		{
			newLeafNode(lv_color_7_0, grammarAccess.getEnumValueAccess().getColorSTRINGTerminalRuleCall_1_1_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getEnumValueRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"color",
        		lv_color_7_0, 
        		"STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getEnumValueAccess().getUnorderedGroup_1());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getEnumValueAccess().getUnorderedGroup_1(), 2)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getEnumValueAccess().getUnorderedGroup_1(), 2);
	 				}
					({true}?=>(	otherlv_8='literal' 
    {
    	newLeafNode(otherlv_8, grammarAccess.getEnumValueAccess().getLiteralKeyword_1_2_0());
    }
	otherlv_9='=' 
    {
    	newLeafNode(otherlv_9, grammarAccess.getEnumValueAccess().getEqualsSignKeyword_1_2_1());
    }
(
(
		lv_literal_10_0=RULE_STRING
		{
			newLeafNode(lv_literal_10_0, grammarAccess.getEnumValueAccess().getLiteralSTRINGTerminalRuleCall_1_2_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getEnumValueRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"literal",
        		lv_literal_10_0, 
        		"STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getEnumValueAccess().getUnorderedGroup_1());
	 				}
 				)
			)  

		)+
	  	{getUnorderedGroupHelper().canLeave(grammarAccess.getEnumValueAccess().getUnorderedGroup_1())}?	
	)
)
	{ 
	  getUnorderedGroupHelper().leave(grammarAccess.getEnumValueAccess().getUnorderedGroup_1());
	}

))
;





// Entry rule entryRuleParameterDef
entryRuleParameterDef returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getParameterDefRule()); }
	 iv_ruleParameterDef=ruleParameterDef 
	 { $current=$iv_ruleParameterDef.current; } 
	 EOF 
;

// Rule ParameterDef
ruleParameterDef returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(
    { 
        newCompositeNode(grammarAccess.getParameterDefAccess().getAttributeDefParserRuleCall_0()); 
    }
    this_AttributeDef_0=ruleAttributeDef
    { 
        $current = $this_AttributeDef_0.current; 
        afterParserOrEnumRuleCall();
    }

    |
    { 
        newCompositeNode(grammarAccess.getParameterDefAccess().getReferenceDefParserRuleCall_1()); 
    }
    this_ReferenceDef_1=ruleReferenceDef
    { 
        $current = $this_ReferenceDef_1.current; 
        afterParserOrEnumRuleCall();
    }
)
;





// Entry rule entryRuleAttributeDef
entryRuleAttributeDef returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getAttributeDefRule()); }
	 iv_ruleAttributeDef=ruleAttributeDef 
	 { $current=$iv_ruleAttributeDef.current; } 
	 EOF 
;

// Rule AttributeDef
ruleAttributeDef returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='attribute' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getAttributeDefAccess().getAttributeKeyword_0());
    }
(
(
		lv_name_1_0=RULE_ID
		{
			newLeafNode(lv_name_1_0, grammarAccess.getAttributeDefAccess().getNameIDTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getAttributeDefRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"name",
        		lv_name_1_0, 
        		"ID");
	    }

)
)(
(
		lv_type_2_0=RULE_STRING
		{
			newLeafNode(lv_type_2_0, grammarAccess.getAttributeDefAccess().getTypeSTRINGTerminalRuleCall_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getAttributeDefRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"type",
        		lv_type_2_0, 
        		"STRING");
	    }

)
)	otherlv_3='{' 
    {
    	newLeafNode(otherlv_3, grammarAccess.getAttributeDefAccess().getLeftCurlyBracketKeyword_3());
    }
(

(
	{ 
	  getUnorderedGroupHelper().enter(grammarAccess.getAttributeDefAccess().getUnorderedGroup_4());
	}
	(
		(

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getAttributeDefAccess().getUnorderedGroup_4(), 0)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getAttributeDefAccess().getUnorderedGroup_4(), 0);
	 				}
					({true}?=>(	otherlv_5='defaultValueLiteral' 
    {
    	newLeafNode(otherlv_5, grammarAccess.getAttributeDefAccess().getDefaultValueLiteralKeyword_4_0_0());
    }
	otherlv_6='=' 
    {
    	newLeafNode(otherlv_6, grammarAccess.getAttributeDefAccess().getEqualsSignKeyword_4_0_1());
    }
(
(
		lv_defaultValueLiteral_7_0=RULE_STRING
		{
			newLeafNode(lv_defaultValueLiteral_7_0, grammarAccess.getAttributeDefAccess().getDefaultValueLiteralSTRINGTerminalRuleCall_4_0_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getAttributeDefRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"defaultValueLiteral",
        		lv_defaultValueLiteral_7_0, 
        		"STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getAttributeDefAccess().getUnorderedGroup_4());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getAttributeDefAccess().getUnorderedGroup_4(), 1)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getAttributeDefAccess().getUnorderedGroup_4(), 1);
	 				}
					({true}?=>(	otherlv_8='description' 
    {
    	newLeafNode(otherlv_8, grammarAccess.getAttributeDefAccess().getDescriptionKeyword_4_1_0());
    }
	otherlv_9='=' 
    {
    	newLeafNode(otherlv_9, grammarAccess.getAttributeDefAccess().getEqualsSignKeyword_4_1_1());
    }
(
(
		lv_description_10_0=RULE_STRING
		{
			newLeafNode(lv_description_10_0, grammarAccess.getAttributeDefAccess().getDescriptionSTRINGTerminalRuleCall_4_1_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getAttributeDefRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"description",
        		lv_description_10_0, 
        		"STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getAttributeDefAccess().getUnorderedGroup_4());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getAttributeDefAccess().getUnorderedGroup_4(), 2)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getAttributeDefAccess().getUnorderedGroup_4(), 2);
	 				}
					({true}?=>(	otherlv_11='shortDescription' 
    {
    	newLeafNode(otherlv_11, grammarAccess.getAttributeDefAccess().getShortDescriptionKeyword_4_2_0());
    }
	otherlv_12='=' 
    {
    	newLeafNode(otherlv_12, grammarAccess.getAttributeDefAccess().getEqualsSignKeyword_4_2_1());
    }
(
(
		lv_shortDescription_13_0=RULE_STRING
		{
			newLeafNode(lv_shortDescription_13_0, grammarAccess.getAttributeDefAccess().getShortDescriptionSTRINGTerminalRuleCall_4_2_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getAttributeDefRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"shortDescription",
        		lv_shortDescription_13_0, 
        		"STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getAttributeDefAccess().getUnorderedGroup_4());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getAttributeDefAccess().getUnorderedGroup_4(), 3)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getAttributeDefAccess().getUnorderedGroup_4(), 3);
	 				}
					({true}?=>(	otherlv_14='units' 
    {
    	newLeafNode(otherlv_14, grammarAccess.getAttributeDefAccess().getUnitsKeyword_4_3_0());
    }
	otherlv_15='=' 
    {
    	newLeafNode(otherlv_15, grammarAccess.getAttributeDefAccess().getEqualsSignKeyword_4_3_1());
    }
(
(
		lv_units_16_0=RULE_STRING
		{
			newLeafNode(lv_units_16_0, grammarAccess.getAttributeDefAccess().getUnitsSTRINGTerminalRuleCall_4_3_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getAttributeDefRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"units",
        		lv_units_16_0, 
        		"STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getAttributeDefAccess().getUnorderedGroup_4());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getAttributeDefAccess().getUnorderedGroup_4(), 4)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getAttributeDefAccess().getUnorderedGroup_4(), 4);
	 				}
					({true}?=>(	otherlv_17='displayName' 
    {
    	newLeafNode(otherlv_17, grammarAccess.getAttributeDefAccess().getDisplayNameKeyword_4_4_0());
    }
	otherlv_18='=' 
    {
    	newLeafNode(otherlv_18, grammarAccess.getAttributeDefAccess().getEqualsSignKeyword_4_4_1());
    }
(
(
		lv_displayName_19_0=RULE_STRING
		{
			newLeafNode(lv_displayName_19_0, grammarAccess.getAttributeDefAccess().getDisplayNameSTRINGTerminalRuleCall_4_4_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getAttributeDefRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"displayName",
        		lv_displayName_19_0, 
        		"STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getAttributeDefAccess().getUnorderedGroup_4());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getAttributeDefAccess().getUnorderedGroup_4(), 5)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getAttributeDefAccess().getUnorderedGroup_4(), 5);
	 				}
					({true}?=>(	otherlv_20='category' 
    {
    	newLeafNode(otherlv_20, grammarAccess.getAttributeDefAccess().getCategoryKeyword_4_5_0());
    }
	otherlv_21='=' 
    {
    	newLeafNode(otherlv_21, grammarAccess.getAttributeDefAccess().getEqualsSignKeyword_4_5_1());
    }
(
(
		lv_category_22_0=RULE_STRING
		{
			newLeafNode(lv_category_22_0, grammarAccess.getAttributeDefAccess().getCategorySTRINGTerminalRuleCall_4_5_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getAttributeDefRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"category",
        		lv_category_22_0, 
        		"STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getAttributeDefAccess().getUnorderedGroup_4());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getAttributeDefAccess().getUnorderedGroup_4(), 6)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getAttributeDefAccess().getUnorderedGroup_4(), 6);
	 				}
					({true}?=>(	otherlv_23='parameterName' 
    {
    	newLeafNode(otherlv_23, grammarAccess.getAttributeDefAccess().getParameterNameKeyword_4_6_0());
    }
	otherlv_24='=' 
    {
    	newLeafNode(otherlv_24, grammarAccess.getAttributeDefAccess().getEqualsSignKeyword_4_6_1());
    }
(
(
		lv_parameterName_25_0=RULE_STRING
		{
			newLeafNode(lv_parameterName_25_0, grammarAccess.getAttributeDefAccess().getParameterNameSTRINGTerminalRuleCall_4_6_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getAttributeDefRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"parameterName",
        		lv_parameterName_25_0, 
        		"STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getAttributeDefAccess().getUnorderedGroup_4());
	 				}
 				)
			)  

		)*	
	)
)
	{ 
	  getUnorderedGroupHelper().leave(grammarAccess.getAttributeDefAccess().getUnorderedGroup_4());
	}

)(
(
		{ 
	        newCompositeNode(grammarAccess.getAttributeDefAccess().getAnnotationsAnnotationParserRuleCall_5_0()); 
	    }
		lv_annotations_26_0=ruleAnnotation		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getAttributeDefRule());
	        }
       		add(
       			$current, 
       			"annotations",
        		lv_annotations_26_0, 
        		"Annotation");
	        afterParserOrEnumRuleCall();
	    }

)
)*	otherlv_27='}' 
    {
    	newLeafNode(otherlv_27, grammarAccess.getAttributeDefAccess().getRightCurlyBracketKeyword_6());
    }
)
;





// Entry rule entryRuleReferenceDef
entryRuleReferenceDef returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getReferenceDefRule()); }
	 iv_ruleReferenceDef=ruleReferenceDef 
	 { $current=$iv_ruleReferenceDef.current; } 
	 EOF 
;

// Rule ReferenceDef
ruleReferenceDef returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='reference' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getReferenceDefAccess().getReferenceKeyword_0());
    }
(
(
		lv_name_1_0=RULE_ID
		{
			newLeafNode(lv_name_1_0, grammarAccess.getReferenceDefAccess().getNameIDTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getReferenceDefRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"name",
        		lv_name_1_0, 
        		"ID");
	    }

)
)(
(
		lv_type_2_0=RULE_STRING
		{
			newLeafNode(lv_type_2_0, grammarAccess.getReferenceDefAccess().getTypeSTRINGTerminalRuleCall_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getReferenceDefRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"type",
        		lv_type_2_0, 
        		"STRING");
	    }

)
)	otherlv_3='{' 
    {
    	newLeafNode(otherlv_3, grammarAccess.getReferenceDefAccess().getLeftCurlyBracketKeyword_3());
    }
(

(
	{ 
	  getUnorderedGroupHelper().enter(grammarAccess.getReferenceDefAccess().getUnorderedGroup_4());
	}
	(
		(

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getReferenceDefAccess().getUnorderedGroup_4(), 0)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getReferenceDefAccess().getUnorderedGroup_4(), 0);
	 				}
					({true}?=>(	otherlv_5='description' 
    {
    	newLeafNode(otherlv_5, grammarAccess.getReferenceDefAccess().getDescriptionKeyword_4_0_0());
    }
	otherlv_6='=' 
    {
    	newLeafNode(otherlv_6, grammarAccess.getReferenceDefAccess().getEqualsSignKeyword_4_0_1());
    }
(
(
		lv_description_7_0=RULE_STRING
		{
			newLeafNode(lv_description_7_0, grammarAccess.getReferenceDefAccess().getDescriptionSTRINGTerminalRuleCall_4_0_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getReferenceDefRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"description",
        		lv_description_7_0, 
        		"STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getReferenceDefAccess().getUnorderedGroup_4());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getReferenceDefAccess().getUnorderedGroup_4(), 1)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getReferenceDefAccess().getUnorderedGroup_4(), 1);
	 				}
					({true}?=>(	otherlv_8='displayName' 
    {
    	newLeafNode(otherlv_8, grammarAccess.getReferenceDefAccess().getDisplayNameKeyword_4_1_0());
    }
	otherlv_9='=' 
    {
    	newLeafNode(otherlv_9, grammarAccess.getReferenceDefAccess().getEqualsSignKeyword_4_1_1());
    }
(
(
		lv_displayName_10_0=RULE_STRING
		{
			newLeafNode(lv_displayName_10_0, grammarAccess.getReferenceDefAccess().getDisplayNameSTRINGTerminalRuleCall_4_1_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getReferenceDefRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"displayName",
        		lv_displayName_10_0, 
        		"STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getReferenceDefAccess().getUnorderedGroup_4());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getReferenceDefAccess().getUnorderedGroup_4(), 2)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getReferenceDefAccess().getUnorderedGroup_4(), 2);
	 				}
					({true}?=>(	otherlv_11='category' 
    {
    	newLeafNode(otherlv_11, grammarAccess.getReferenceDefAccess().getCategoryKeyword_4_2_0());
    }
	otherlv_12='=' 
    {
    	newLeafNode(otherlv_12, grammarAccess.getReferenceDefAccess().getEqualsSignKeyword_4_2_1());
    }
(
(
		lv_category_13_0=RULE_STRING
		{
			newLeafNode(lv_category_13_0, grammarAccess.getReferenceDefAccess().getCategorySTRINGTerminalRuleCall_4_2_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getReferenceDefRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"category",
        		lv_category_13_0, 
        		"STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getReferenceDefAccess().getUnorderedGroup_4());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getReferenceDefAccess().getUnorderedGroup_4(), 3)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getReferenceDefAccess().getUnorderedGroup_4(), 3);
	 				}
					({true}?=>(	otherlv_14='containment' 
    {
    	newLeafNode(otherlv_14, grammarAccess.getReferenceDefAccess().getContainmentKeyword_4_3_0());
    }
	otherlv_15='=' 
    {
    	newLeafNode(otherlv_15, grammarAccess.getReferenceDefAccess().getEqualsSignKeyword_4_3_1());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getReferenceDefAccess().getContainmentBooleanParserRuleCall_4_3_2_0()); 
	    }
		lv_containment_16_0=ruleBoolean		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getReferenceDefRule());
	        }
       		set(
       			$current, 
       			"containment",
        		lv_containment_16_0, 
        		"Boolean");
	        afterParserOrEnumRuleCall();
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getReferenceDefAccess().getUnorderedGroup_4());
	 				}
 				)
			)  

		)*	
	)
)
	{ 
	  getUnorderedGroupHelper().leave(grammarAccess.getReferenceDefAccess().getUnorderedGroup_4());
	}

)(
(
		{ 
	        newCompositeNode(grammarAccess.getReferenceDefAccess().getAnnotationsAnnotationParserRuleCall_5_0()); 
	    }
		lv_annotations_17_0=ruleAnnotation		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getReferenceDefRule());
	        }
       		add(
       			$current, 
       			"annotations",
        		lv_annotations_17_0, 
        		"Annotation");
	        afterParserOrEnumRuleCall();
	    }

)
)*(
(
		{ 
	        newCompositeNode(grammarAccess.getReferenceDefAccess().getRequirementsRequirementParserRuleCall_6_0()); 
	    }
		lv_requirements_18_0=ruleRequirement		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getReferenceDefRule());
	        }
       		add(
       			$current, 
       			"requirements",
        		lv_requirements_18_0, 
        		"Requirement");
	        afterParserOrEnumRuleCall();
	    }

)
)*(
(
		{ 
	        newCompositeNode(grammarAccess.getReferenceDefAccess().getEffectsEffectParserRuleCall_7_0()); 
	    }
		lv_effects_19_0=ruleEffect		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getReferenceDefRule());
	        }
       		add(
       			$current, 
       			"effects",
        		lv_effects_19_0, 
        		"Effect");
	        afterParserOrEnumRuleCall();
	    }

)
)*	otherlv_20='}' 
    {
    	newLeafNode(otherlv_20, grammarAccess.getReferenceDefAccess().getRightCurlyBracketKeyword_8());
    }
)
;





// Entry rule entryRuleBoolean
entryRuleBoolean returns [String current=null] 
	:
	{ newCompositeNode(grammarAccess.getBooleanRule()); } 
	 iv_ruleBoolean=ruleBoolean 
	 { $current=$iv_ruleBoolean.current.getText(); }  
	 EOF 
;

// Rule Boolean
ruleBoolean returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(
	kw='true' 
    {
        $current.merge(kw);
        newLeafNode(kw, grammarAccess.getBooleanAccess().getTrueKeyword_0()); 
    }

    |
	kw='false' 
    {
        $current.merge(kw);
        newLeafNode(kw, grammarAccess.getBooleanAccess().getFalseKeyword_1()); 
    }
)
    ;





// Entry rule entryRuleActivityDef
entryRuleActivityDef returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getActivityDefRule()); }
	 iv_ruleActivityDef=ruleActivityDef 
	 { $current=$iv_ruleActivityDef.current; } 
	 EOF 
;

// Rule ActivityDef
ruleActivityDef returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='ActivityDef' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getActivityDefAccess().getActivityDefKeyword_0());
    }
(
(
		lv_name_1_0=RULE_ID
		{
			newLeafNode(lv_name_1_0, grammarAccess.getActivityDefAccess().getNameIDTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getActivityDefRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"name",
        		lv_name_1_0, 
        		"ID");
	    }

)
)	otherlv_2='{' 
    {
    	newLeafNode(otherlv_2, grammarAccess.getActivityDefAccess().getLeftCurlyBracketKeyword_2());
    }
(

(
	{ 
	  getUnorderedGroupHelper().enter(grammarAccess.getActivityDefAccess().getUnorderedGroup_3());
	}
	(
		(

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getActivityDefAccess().getUnorderedGroup_3(), 0)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getActivityDefAccess().getUnorderedGroup_3(), 0);
	 				}
					({true}?=>(	otherlv_4='description' 
    {
    	newLeafNode(otherlv_4, grammarAccess.getActivityDefAccess().getDescriptionKeyword_3_0_0());
    }
	otherlv_5='=' 
    {
    	newLeafNode(otherlv_5, grammarAccess.getActivityDefAccess().getEqualsSignKeyword_3_0_1());
    }
(
(
		lv_description_6_0=RULE_STRING
		{
			newLeafNode(lv_description_6_0, grammarAccess.getActivityDefAccess().getDescriptionSTRINGTerminalRuleCall_3_0_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getActivityDefRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"description",
        		lv_description_6_0, 
        		"STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getActivityDefAccess().getUnorderedGroup_3());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getActivityDefAccess().getUnorderedGroup_3(), 1)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getActivityDefAccess().getUnorderedGroup_3(), 1);
	 				}
					({true}?=>(	otherlv_7='category' 
    {
    	newLeafNode(otherlv_7, grammarAccess.getActivityDefAccess().getCategoryKeyword_3_1_0());
    }
	otherlv_8='=' 
    {
    	newLeafNode(otherlv_8, grammarAccess.getActivityDefAccess().getEqualsSignKeyword_3_1_1());
    }
(
(
		lv_category_9_0=RULE_STRING
		{
			newLeafNode(lv_category_9_0, grammarAccess.getActivityDefAccess().getCategorySTRINGTerminalRuleCall_3_1_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getActivityDefRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"category",
        		lv_category_9_0, 
        		"STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getActivityDefAccess().getUnorderedGroup_3());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getActivityDefAccess().getUnorderedGroup_3(), 2)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getActivityDefAccess().getUnorderedGroup_3(), 2);
	 				}
					({true}?=>(	otherlv_10='duration' 
    {
    	newLeafNode(otherlv_10, grammarAccess.getActivityDefAccess().getDurationKeyword_3_2_0());
    }
	otherlv_11='=' 
    {
    	newLeafNode(otherlv_11, grammarAccess.getActivityDefAccess().getEqualsSignKeyword_3_2_1());
    }
(
(
		lv_duration_12_0=RULE_STRING
		{
			newLeafNode(lv_duration_12_0, grammarAccess.getActivityDefAccess().getDurationSTRINGTerminalRuleCall_3_2_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getActivityDefRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"duration",
        		lv_duration_12_0, 
        		"STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getActivityDefAccess().getUnorderedGroup_3());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getActivityDefAccess().getUnorderedGroup_3(), 3)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getActivityDefAccess().getUnorderedGroup_3(), 3);
	 				}
					({true}?=>(	otherlv_13='displayName' 
    {
    	newLeafNode(otherlv_13, grammarAccess.getActivityDefAccess().getDisplayNameKeyword_3_3_0());
    }
	otherlv_14='=' 
    {
    	newLeafNode(otherlv_14, grammarAccess.getActivityDefAccess().getEqualsSignKeyword_3_3_1());
    }
(
(
		lv_displayName_15_0=RULE_STRING
		{
			newLeafNode(lv_displayName_15_0, grammarAccess.getActivityDefAccess().getDisplayNameSTRINGTerminalRuleCall_3_3_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getActivityDefRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"displayName",
        		lv_displayName_15_0, 
        		"STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getActivityDefAccess().getUnorderedGroup_3());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getActivityDefAccess().getUnorderedGroup_3(), 4)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getActivityDefAccess().getUnorderedGroup_3(), 4);
	 				}
					({true}?=>(	otherlv_16='hidden' 
    {
    	newLeafNode(otherlv_16, grammarAccess.getActivityDefAccess().getHiddenKeyword_3_4_0());
    }
	otherlv_17='=' 
    {
    	newLeafNode(otherlv_17, grammarAccess.getActivityDefAccess().getEqualsSignKeyword_3_4_1());
    }
(
(
		lv_hiddenParams_18_0=RULE_STRING
		{
			newLeafNode(lv_hiddenParams_18_0, grammarAccess.getActivityDefAccess().getHiddenParamsSTRINGTerminalRuleCall_3_4_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getActivityDefRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"hiddenParams",
        		lv_hiddenParams_18_0, 
        		"STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getActivityDefAccess().getUnorderedGroup_3());
	 				}
 				)
			)  

		)*	
	)
)
	{ 
	  getUnorderedGroupHelper().leave(grammarAccess.getActivityDefAccess().getUnorderedGroup_3());
	}

)(
(
		{ 
	        newCompositeNode(grammarAccess.getActivityDefAccess().getAnnotationsAnnotationParserRuleCall_4_0()); 
	    }
		lv_annotations_19_0=ruleAnnotation		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getActivityDefRule());
	        }
       		add(
       			$current, 
       			"annotations",
        		lv_annotations_19_0, 
        		"Annotation");
	        afterParserOrEnumRuleCall();
	    }

)
)*(
(
		{ 
	        newCompositeNode(grammarAccess.getActivityDefAccess().getParametersParameterDefParserRuleCall_5_0()); 
	    }
		lv_parameters_20_0=ruleParameterDef		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getActivityDefRule());
	        }
       		add(
       			$current, 
       			"parameters",
        		lv_parameters_20_0, 
        		"ParameterDef");
	        afterParserOrEnumRuleCall();
	    }

)
)*(
(
		{ 
	        newCompositeNode(grammarAccess.getActivityDefAccess().getRequirementsRequirementParserRuleCall_6_0()); 
	    }
		lv_requirements_21_0=ruleRequirement		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getActivityDefRule());
	        }
       		add(
       			$current, 
       			"requirements",
        		lv_requirements_21_0, 
        		"Requirement");
	        afterParserOrEnumRuleCall();
	    }

)
)*(
(
		{ 
	        newCompositeNode(grammarAccess.getActivityDefAccess().getEffectsEffectParserRuleCall_7_0()); 
	    }
		lv_effects_22_0=ruleEffect		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getActivityDefRule());
	        }
       		add(
       			$current, 
       			"effects",
        		lv_effects_22_0, 
        		"Effect");
	        afterParserOrEnumRuleCall();
	    }

)
)*	otherlv_23='}' 
    {
    	newLeafNode(otherlv_23, grammarAccess.getActivityDefAccess().getRightCurlyBracketKeyword_8());
    }
)
;





// Entry rule entryRuleAnnotation
entryRuleAnnotation returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getAnnotationRule()); }
	 iv_ruleAnnotation=ruleAnnotation 
	 { $current=$iv_ruleAnnotation.current; } 
	 EOF 
;

// Rule Annotation
ruleAnnotation returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='annotation' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getAnnotationAccess().getAnnotationKeyword_0());
    }
(
(
		lv_source_1_0=RULE_STRING
		{
			newLeafNode(lv_source_1_0, grammarAccess.getAnnotationAccess().getSourceSTRINGTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getAnnotationRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"source",
        		lv_source_1_0, 
        		"STRING");
	    }

)
)(
(
		lv_key_2_0=RULE_STRING
		{
			newLeafNode(lv_key_2_0, grammarAccess.getAnnotationAccess().getKeySTRINGTerminalRuleCall_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getAnnotationRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"key",
        		lv_key_2_0, 
        		"STRING");
	    }

)
)(
(
		lv_value_3_0=RULE_STRING
		{
			newLeafNode(lv_value_3_0, grammarAccess.getAnnotationAccess().getValueSTRINGTerminalRuleCall_3_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getAnnotationRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"value",
        		lv_value_3_0, 
        		"STRING");
	    }

)
))
;





// Entry rule entryRuleRequirement
entryRuleRequirement returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getRequirementRule()); }
	 iv_ruleRequirement=ruleRequirement 
	 { $current=$iv_ruleRequirement.current; } 
	 EOF 
;

// Rule Requirement
ruleRequirement returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(
    { 
        newCompositeNode(grammarAccess.getRequirementAccess().getNumericRequirementParserRuleCall_0()); 
    }
    this_NumericRequirement_0=ruleNumericRequirement
    { 
        $current = $this_NumericRequirement_0.current; 
        afterParserOrEnumRuleCall();
    }

    |
    { 
        newCompositeNode(grammarAccess.getRequirementAccess().getStateRequirementParserRuleCall_1()); 
    }
    this_StateRequirement_1=ruleStateRequirement
    { 
        $current = $this_StateRequirement_1.current; 
        afterParserOrEnumRuleCall();
    }
)
;





// Entry rule entryRuleNumericRequirement
entryRuleNumericRequirement returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getNumericRequirementRule()); }
	 iv_ruleNumericRequirement=ruleNumericRequirement 
	 { $current=$iv_ruleNumericRequirement.current; } 
	 EOF 
;

// Rule NumericRequirement
ruleNumericRequirement returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='numericRequirement' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getNumericRequirementAccess().getNumericRequirementKeyword_0());
    }
	otherlv_1='expression' 
    {
    	newLeafNode(otherlv_1, grammarAccess.getNumericRequirementAccess().getExpressionKeyword_1());
    }
	otherlv_2='=' 
    {
    	newLeafNode(otherlv_2, grammarAccess.getNumericRequirementAccess().getEqualsSignKeyword_2());
    }
(
(
		lv_expression_3_0=RULE_STRING
		{
			newLeafNode(lv_expression_3_0, grammarAccess.getNumericRequirementAccess().getExpressionSTRINGTerminalRuleCall_3_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getNumericRequirementRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"expression",
        		lv_expression_3_0, 
        		"STRING");
	    }

)
))
;





// Entry rule entryRuleStateRequirement
entryRuleStateRequirement returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getStateRequirementRule()); }
	 iv_ruleStateRequirement=ruleStateRequirement 
	 { $current=$iv_ruleStateRequirement.current; } 
	 EOF 
;

// Rule StateRequirement
ruleStateRequirement returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='stateRequirement' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getStateRequirementAccess().getStateRequirementKeyword_0());
    }
(

(
	{ 
	  getUnorderedGroupHelper().enter(grammarAccess.getStateRequirementAccess().getUnorderedGroup_1());
	}
	(
		(

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getStateRequirementAccess().getUnorderedGroup_1(), 0)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getStateRequirementAccess().getUnorderedGroup_1(), 0);
	 				}
					({true}?=>(	otherlv_2='definition' 
    {
    	newLeafNode(otherlv_2, grammarAccess.getStateRequirementAccess().getDefinitionKeyword_1_0_0());
    }
	otherlv_3='=' 
    {
    	newLeafNode(otherlv_3, grammarAccess.getStateRequirementAccess().getEqualsSignKeyword_1_0_1());
    }
(
(
		lv_definition_4_0=RULE_STRING
		{
			newLeafNode(lv_definition_4_0, grammarAccess.getStateRequirementAccess().getDefinitionSTRINGTerminalRuleCall_1_0_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getStateRequirementRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"definition",
        		lv_definition_4_0, 
        		"STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getStateRequirementAccess().getUnorderedGroup_1());
	 				}
 				)
			)  |

			( 
				{getUnorderedGroupHelper().canSelect(grammarAccess.getStateRequirementAccess().getUnorderedGroup_1(), 1)}?=>(
					{ 
	 				  getUnorderedGroupHelper().select(grammarAccess.getStateRequirementAccess().getUnorderedGroup_1(), 1);
	 				}
					({true}?=>(	otherlv_5='requiredState' 
    {
    	newLeafNode(otherlv_5, grammarAccess.getStateRequirementAccess().getRequiredStateKeyword_1_1_0());
    }
	otherlv_6='=' 
    {
    	newLeafNode(otherlv_6, grammarAccess.getStateRequirementAccess().getEqualsSignKeyword_1_1_1());
    }
(
(
		lv_requiredState_7_0=RULE_STRING
		{
			newLeafNode(lv_requiredState_7_0, grammarAccess.getStateRequirementAccess().getRequiredStateSTRINGTerminalRuleCall_1_1_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getStateRequirementRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"requiredState",
        		lv_requiredState_7_0, 
        		"STRING");
	    }

)
)))
					{ 
	 				  getUnorderedGroupHelper().returnFromSelection(grammarAccess.getStateRequirementAccess().getUnorderedGroup_1());
	 				}
 				)
			)  

		)+
	  	{getUnorderedGroupHelper().canLeave(grammarAccess.getStateRequirementAccess().getUnorderedGroup_1())}?	
	)
)
	{ 
	  getUnorderedGroupHelper().leave(grammarAccess.getStateRequirementAccess().getUnorderedGroup_1());
	}

))
;





// Entry rule entryRuleEffect
entryRuleEffect returns [String current=null] 
	:
	{ newCompositeNode(grammarAccess.getEffectRule()); } 
	 iv_ruleEffect=ruleEffect 
	 { $current=$iv_ruleEffect.current.getText(); }  
	 EOF 
;

// Rule Effect
ruleEffect returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(
    { 
        newCompositeNode(grammarAccess.getEffectAccess().getNumericEffectParserRuleCall_0()); 
    }
    this_NumericEffect_0=ruleNumericEffect    {
		$current.merge(this_NumericEffect_0);
    }

    { 
        afterParserOrEnumRuleCall();
    }

    |
    { 
        newCompositeNode(grammarAccess.getEffectAccess().getStateEffectParserRuleCall_1()); 
    }
    this_StateEffect_1=ruleStateEffect    {
		$current.merge(this_StateEffect_1);
    }

    { 
        afterParserOrEnumRuleCall();
    }

    |
    { 
        newCompositeNode(grammarAccess.getEffectAccess().getClaimableEffectParserRuleCall_2()); 
    }
    this_ClaimableEffect_2=ruleClaimableEffect    {
		$current.merge(this_ClaimableEffect_2);
    }

    { 
        afterParserOrEnumRuleCall();
    }

    |
    { 
        newCompositeNode(grammarAccess.getEffectAccess().getSharedEffectParserRuleCall_3()); 
    }
    this_SharedEffect_3=ruleSharedEffect    {
		$current.merge(this_SharedEffect_3);
    }

    { 
        afterParserOrEnumRuleCall();
    }
)
    ;





// Entry rule entryRuleNumericEffect
entryRuleNumericEffect returns [String current=null] 
	:
	{ newCompositeNode(grammarAccess.getNumericEffectRule()); } 
	 iv_ruleNumericEffect=ruleNumericEffect 
	 { $current=$iv_ruleNumericEffect.current.getText(); }  
	 EOF 
;

// Rule NumericEffect
ruleNumericEffect returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:

	kw='numericEffect' 
    {
        $current.merge(kw);
        newLeafNode(kw, grammarAccess.getNumericEffectAccess().getNumericEffectKeyword()); 
    }

    ;





// Entry rule entryRuleStateEffect
entryRuleStateEffect returns [String current=null] 
	:
	{ newCompositeNode(grammarAccess.getStateEffectRule()); } 
	 iv_ruleStateEffect=ruleStateEffect 
	 { $current=$iv_ruleStateEffect.current.getText(); }  
	 EOF 
;

// Rule StateEffect
ruleStateEffect returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:

	kw='stateEffect' 
    {
        $current.merge(kw);
        newLeafNode(kw, grammarAccess.getStateEffectAccess().getStateEffectKeyword()); 
    }

    ;





// Entry rule entryRuleClaimableEffect
entryRuleClaimableEffect returns [String current=null] 
	:
	{ newCompositeNode(grammarAccess.getClaimableEffectRule()); } 
	 iv_ruleClaimableEffect=ruleClaimableEffect 
	 { $current=$iv_ruleClaimableEffect.current.getText(); }  
	 EOF 
;

// Rule ClaimableEffect
ruleClaimableEffect returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:

	kw='claimableEffect' 
    {
        $current.merge(kw);
        newLeafNode(kw, grammarAccess.getClaimableEffectAccess().getClaimableEffectKeyword()); 
    }

    ;





// Entry rule entryRuleSharedEffect
entryRuleSharedEffect returns [String current=null] 
	:
	{ newCompositeNode(grammarAccess.getSharedEffectRule()); } 
	 iv_ruleSharedEffect=ruleSharedEffect 
	 { $current=$iv_ruleSharedEffect.current.getText(); }  
	 EOF 
;

// Rule SharedEffect
ruleSharedEffect returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:

	kw='sharedEffect' 
    {
        $current.merge(kw);
        newLeafNode(kw, grammarAccess.getSharedEffectAccess().getSharedEffectKeyword()); 
    }

    ;





// Entry rule entryRuleActivityGroupDef
entryRuleActivityGroupDef returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getActivityGroupDefRule()); }
	 iv_ruleActivityGroupDef=ruleActivityGroupDef 
	 { $current=$iv_ruleActivityGroupDef.current; } 
	 EOF 
;

// Rule ActivityGroupDef
ruleActivityGroupDef returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='ActivityGroupDef' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getActivityGroupDefAccess().getActivityGroupDefKeyword_0());
    }
(
(
		lv_name_1_0=RULE_ID
		{
			newLeafNode(lv_name_1_0, grammarAccess.getActivityGroupDefAccess().getNameIDTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getActivityGroupDefRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"name",
        		lv_name_1_0, 
        		"ID");
	    }

)
)	otherlv_2='{' 
    {
    	newLeafNode(otherlv_2, grammarAccess.getActivityGroupDefAccess().getLeftCurlyBracketKeyword_2());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getActivityGroupDefAccess().getAnnotationsAnnotationParserRuleCall_3_0()); 
	    }
		lv_annotations_3_0=ruleAnnotation		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getActivityGroupDefRule());
	        }
       		add(
       			$current, 
       			"annotations",
        		lv_annotations_3_0, 
        		"Annotation");
	        afterParserOrEnumRuleCall();
	    }

)
)*(
(
		{ 
	        newCompositeNode(grammarAccess.getActivityGroupDefAccess().getParametersParameterDefParserRuleCall_4_0()); 
	    }
		lv_parameters_4_0=ruleParameterDef		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getActivityGroupDefRule());
	        }
       		add(
       			$current, 
       			"parameters",
        		lv_parameters_4_0, 
        		"ParameterDef");
	        afterParserOrEnumRuleCall();
	    }

)
)*	otherlv_5='}' 
    {
    	newLeafNode(otherlv_5, grammarAccess.getActivityGroupDefAccess().getRightCurlyBracketKeyword_5());
    }
)
;





// Entry rule entryRuleObjectDef
entryRuleObjectDef returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getObjectDefRule()); }
	 iv_ruleObjectDef=ruleObjectDef 
	 { $current=$iv_ruleObjectDef.current; } 
	 EOF 
;

// Rule ObjectDef
ruleObjectDef returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='ObjectDef' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getObjectDefAccess().getObjectDefKeyword_0());
    }
(
(
		lv_name_1_0=RULE_ID
		{
			newLeafNode(lv_name_1_0, grammarAccess.getObjectDefAccess().getNameIDTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getObjectDefRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"name",
        		lv_name_1_0, 
        		"ID");
	    }

)
))
;





// Entry rule entryRuleResourceDef
entryRuleResourceDef returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getResourceDefRule()); }
	 iv_ruleResourceDef=ruleResourceDef 
	 { $current=$iv_ruleResourceDef.current; } 
	 EOF 
;

// Rule ResourceDef
ruleResourceDef returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(
    { 
        newCompositeNode(grammarAccess.getResourceDefAccess().getNumericResourceParserRuleCall_0()); 
    }
    this_NumericResource_0=ruleNumericResource
    { 
        $current = $this_NumericResource_0.current; 
        afterParserOrEnumRuleCall();
    }

    |
    { 
        newCompositeNode(grammarAccess.getResourceDefAccess().getStateResourceParserRuleCall_1()); 
    }
    this_StateResource_1=ruleStateResource
    { 
        $current = $this_StateResource_1.current; 
        afterParserOrEnumRuleCall();
    }

    |
    { 
        newCompositeNode(grammarAccess.getResourceDefAccess().getClaimableResourceParserRuleCall_2()); 
    }
    this_ClaimableResource_2=ruleClaimableResource
    { 
        $current = $this_ClaimableResource_2.current; 
        afterParserOrEnumRuleCall();
    }

    |
    { 
        newCompositeNode(grammarAccess.getResourceDefAccess().getSharableResourceParserRuleCall_3()); 
    }
    this_SharableResource_3=ruleSharableResource
    { 
        $current = $this_SharableResource_3.current; 
        afterParserOrEnumRuleCall();
    }

    |
    { 
        newCompositeNode(grammarAccess.getResourceDefAccess().getSummaryResourceParserRuleCall_4()); 
    }
    this_SummaryResource_4=ruleSummaryResource
    { 
        $current = $this_SummaryResource_4.current; 
        afterParserOrEnumRuleCall();
    }
)
;





// Entry rule entryRuleNumericResource
entryRuleNumericResource returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getNumericResourceRule()); }
	 iv_ruleNumericResource=ruleNumericResource 
	 { $current=$iv_ruleNumericResource.current; } 
	 EOF 
;

// Rule NumericResource
ruleNumericResource returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='NumericResource' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getNumericResourceAccess().getNumericResourceKeyword_0());
    }
(
(
		lv_name_1_0=RULE_ID
		{
			newLeafNode(lv_name_1_0, grammarAccess.getNumericResourceAccess().getNameIDTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getNumericResourceRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"name",
        		lv_name_1_0, 
        		"ID");
	    }

)
))
;





// Entry rule entryRuleStateResource
entryRuleStateResource returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getStateResourceRule()); }
	 iv_ruleStateResource=ruleStateResource 
	 { $current=$iv_ruleStateResource.current; } 
	 EOF 
;

// Rule StateResource
ruleStateResource returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='StateResource' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getStateResourceAccess().getStateResourceKeyword_0());
    }
(
(
		lv_name_1_0=RULE_ID
		{
			newLeafNode(lv_name_1_0, grammarAccess.getStateResourceAccess().getNameIDTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getStateResourceRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"name",
        		lv_name_1_0, 
        		"ID");
	    }

)
))
;





// Entry rule entryRuleClaimableResource
entryRuleClaimableResource returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getClaimableResourceRule()); }
	 iv_ruleClaimableResource=ruleClaimableResource 
	 { $current=$iv_ruleClaimableResource.current; } 
	 EOF 
;

// Rule ClaimableResource
ruleClaimableResource returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='ClaimableResource' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getClaimableResourceAccess().getClaimableResourceKeyword_0());
    }
(
(
		lv_name_1_0=RULE_ID
		{
			newLeafNode(lv_name_1_0, grammarAccess.getClaimableResourceAccess().getNameIDTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getClaimableResourceRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"name",
        		lv_name_1_0, 
        		"ID");
	    }

)
))
;





// Entry rule entryRuleSharableResource
entryRuleSharableResource returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getSharableResourceRule()); }
	 iv_ruleSharableResource=ruleSharableResource 
	 { $current=$iv_ruleSharableResource.current; } 
	 EOF 
;

// Rule SharableResource
ruleSharableResource returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='SharableResource' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getSharableResourceAccess().getSharableResourceKeyword_0());
    }
(
(
		lv_name_1_0=RULE_ID
		{
			newLeafNode(lv_name_1_0, grammarAccess.getSharableResourceAccess().getNameIDTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getSharableResourceRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"name",
        		lv_name_1_0, 
        		"ID");
	    }

)
))
;





// Entry rule entryRuleSummaryResource
entryRuleSummaryResource returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getSummaryResourceRule()); }
	 iv_ruleSummaryResource=ruleSummaryResource 
	 { $current=$iv_ruleSummaryResource.current; } 
	 EOF 
;

// Rule SummaryResource
ruleSummaryResource returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(	otherlv_0='Summaryresource' 
    {
    	newLeafNode(otherlv_0, grammarAccess.getSummaryResourceAccess().getSummaryresourceKeyword_0());
    }
(
(
		lv_name_1_0=RULE_ID
		{
			newLeafNode(lv_name_1_0, grammarAccess.getSummaryResourceAccess().getNameIDTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getSummaryResourceRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"name",
        		lv_name_1_0, 
        		"ID");
	    }

)
))
;





RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' ('b'|'t'|'n'|'f'|'r'|'u'|'"'|'\''|'\\')|~(('\\'|'"')))* '"'|'\'' ('\\' ('b'|'t'|'n'|'f'|'r'|'u'|'"'|'\''|'\\')|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;


