/*
 * generated by Xtext
 */
package gov.nasa.ensemble.dictionary.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XDictionaryUiModule extends gov.nasa.ensemble.dictionary.xtext.ui.AbstractXDictionaryUiModule {
	public XDictionaryUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
