/**
 * generated by Xtext
 */
package gov.nasa.ensemble.dictionary.xtext.validation;

import gov.nasa.ensemble.dictionary.xtext.validation.AbstractXDictionaryValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class XDictionaryValidator extends AbstractXDictionaryValidator {
}
