/*
 * generated by Xtext
 */
package gov.nasa.ensemble.dictionary.xtext.ui.contentassist

import gov.nasa.ensemble.dictionary.xtext.ui.contentassist.AbstractXDictionaryProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class XDictionaryProposalProvider extends AbstractXDictionaryProposalProvider {
}
